version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine # Use a stable version
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tron_wallet
      POSTGRES_PASSWORD: tron
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
